# Restricted Boltzmann Machine (RBM) To Recommend Movies

In [1]:
import numpy as np
import rbm

In [24]:
rbm1 = rbm.RBM(num_visible= 6, num_hidden= 2)

In [25]:
dataset = np.array([
    [1,1,1,0,0,0],
    [1,0,1,0,0,0],
    [1,1,1,0,0,0],
    [0,0,1,1,1,1], 
    [0,0,1,1,0,1],
    [0,0,1,1,0,1]
])

dataset.shape

(6, 6)

In [26]:
movies = ["A bruxa", "Invocação do mal", "O chamado", "Se beber não case", "Gente grande", "American pie"]

In [27]:
rbm1.train(dataset, max_epochs= 5000)

Epoch 0: error is 9.134716986185564
Epoch 1: error is 8.882975705001819
Epoch 2: error is 8.744043467602154
Epoch 3: error is 8.654151532755762
Epoch 4: error is 8.422561700977994
Epoch 5: error is 8.293135170157736
Epoch 6: error is 8.334383591422927
Epoch 7: error is 8.092537228684517
Epoch 8: error is 8.152271073171143
Epoch 9: error is 7.923836674082915
Epoch 10: error is 7.849241291085709
Epoch 11: error is 7.870289536627693
Epoch 12: error is 7.79178983290398
Epoch 13: error is 7.503015245536982
Epoch 14: error is 7.662570488557813
Epoch 15: error is 7.637345767838616
Epoch 16: error is 7.572473381448803
Epoch 17: error is 7.304894796473857
Epoch 18: error is 7.195319549699315
Epoch 19: error is 7.553449284652161
Epoch 20: error is 7.289391246101791
Epoch 21: error is 7.268820542575695
Epoch 22: error is 7.256429877992928
Epoch 23: error is 7.044133180690356
Epoch 24: error is 7.054747335030902
Epoch 25: error is 7.371407397669971
Epoch 26: error is 7.1404098808161685
Epoch 27: e

In [28]:
rbm1.weights, rbm1.weights.shape
# the line 0 and column 0 are values of bias

(array([[ 2.47101156,  2.2604744 ,  0.40194334],
        [-1.00043667, -3.35056575,  7.93450812],
        [ 0.27595314, -7.22555602,  3.37475218],
        [ 4.94470434,  3.83744621,  1.90144987],
        [ 0.93312747,  3.63510673, -8.22686179],
        [-1.3218298 ,  0.61685956, -4.54670301],
        [ 0.93834846,  3.6311014 , -8.22942497]]),
 (7, 3))

In [29]:
user1 = np.array([[1,1,0,1,0,0]])

rbm1.run_visible(user1)

array([[0., 1.]])

In [30]:
user2 = np.array([[0,0,0,1,1,0]])

rbm1.run_visible(user2)

array([[1., 0.]])

In [31]:
# we can see that the first hidden neuron is about comedy movies and the second one is about horror movies

In [32]:
hidden_layer = np.array([[1,0]])
recommendation = rbm1.run_hidden(hidden_layer)
recommendation

array([[0., 0., 1., 1., 0., 1.]])

In [33]:
for i in range(len(user1[0])):
    if user2[0, i] == 0 and recommendation[0, i] == 1:
        print(movies[i])

O chamado
American pie


In [2]:
rbm2 = rbm.RBM(num_visible= 6, num_hidden= 3)

movies2 = ["Freedy X Jason", "O ultimato bourne", "Star trek", "Exterminador do futuro", "Norbit", "Star wars"]

dataset2 = np.array([
    [0, 1, 1, 1, 0, 1],
    [1, 1, 0, 1, 1, 1],
    [0, 1, 0, 1, 0, 1],
    [0, 1, 1, 1, 0, 1],
    [1, 1, 0, 1, 0, 1],
    [1, 1, 0, 1, 1, 1]
])

rbm2.train(dataset2, max_epochs= 5000)

Epoch 0: error is 8.972332067845194
Epoch 1: error is 8.5444003538388
Epoch 2: error is 8.12606958374681
Epoch 3: error is 7.751129469367787
Epoch 4: error is 7.168173707693464
Epoch 5: error is 6.771143507971547
Epoch 6: error is 6.313808549271057
Epoch 7: error is 6.113675054565499
Epoch 8: error is 6.059785411865682
Epoch 9: error is 5.815092082082859
Epoch 10: error is 5.482188279984996
Epoch 11: error is 5.807301154986936
Epoch 12: error is 5.197881840440716
Epoch 13: error is 5.218019236735204
Epoch 14: error is 5.442669048797488
Epoch 15: error is 4.9404460609243435
Epoch 16: error is 4.8541814525173
Epoch 17: error is 5.116123063665257
Epoch 18: error is 4.7245424771767315
Epoch 19: error is 4.69485139273226
Epoch 20: error is 4.6885945062456456
Epoch 21: error is 4.678679069090773
Epoch 22: error is 4.5984586943816925
Epoch 23: error is 4.5276202276903135
Epoch 24: error is 4.494969449517991
Epoch 25: error is 4.439406763724579
Epoch 26: error is 4.392218674593538
Epoch 27: er

In [3]:
leonardo = np.array([[0,1,0,1,0,0]])

hidden_layer2 = rbm2.run_visible(leonardo)
hidden_layer2

array([[0., 1., 1.]])

In [4]:
recommendation2 = rbm2.run_hidden(hidden_layer2)
recommendation2

array([[0., 1., 0., 1., 0., 1.]])

In [6]:
for i in range(len(leonardo[0])):
    if leonardo[0, i] == 0 and recommendation2[0, i] == 1:
        print(movies2[i])

Star wars
